### ISSUE TITLE
0.6.0-beta LND not working

### ISSUE THREAD

**Issue by jrosco** [LN-Zap/zap-desktop#1957]
The new version(0.6.0-beta) of LND is not working

## Description
Connecting to a LND node with version 0.6.0-beta screen hangs at "Fetching tickers" having a look it seems to not find the chain

```zap:main ___Inspected object #1___
  zap:main { chains: [],
  zap:main   uris:
  zap:main    [ '' ],
  zap:main   identity_pubkey:
  zap:main    '0329fb983abd98e3ca6f7386dad7717f22b755a455ca9c69adaafed2b5a9fe0f15',
  zap:main   alias: 'DecentPay [ ⚡ LND ⚡ ]',
  zap:main   num_pending_channels: 0,
  zap:main   num_active_channels: 8,
  zap:main   num_peers: 8,
  zap:main   block_height: 570281,
  zap:main   block_hash:
  zap:main    '00000000000000000029d6a91854f1bfec5dd3d9226b084f72dd85aeb2152883',
  zap:main   synced_to_chain: false,
  zap:main   testnet: false,
  zap:main   best_header_timestamp: 1554442512,
  zap:main   version: '0.6.0-beta commit=v0.6-beta-rc2',
  zap:main   num_inactive_channels: 0 } +83ms
  zap:main [INF]  infoData.chains [] +0ms
  zap:main [ERR]  info: TypeError: Cannot read property 'chain' of undefined
  zap:main ___Stack trace #1___
  zap:main TypeError: Cannot read property 'chain' of undefined
  zap:main     at networkController.getInfo.then.infoData (/home/jrosco/GitRepos/other/zap-desktop/lnd/methods/index.js:62:71)
  zap:main     at process._tickCallback (internal/process/next_tick.js:68:7) +1ms 
```

## Expected Behavior

Fetch tickers and startup correctly

## Actual Behavior

Cannot read the chain property and hangs at fetching tickers due to error mention above

## Possible Fix
See error log above

## Your Environment

- Zap version: Zap 0.4.0 Beta
- Operating System and version: Ubuntu 18.04.2 LTS

**Comment by jrosco** [comment]
I added code to print "[INF]  infoData.chains [] +0ms" to to error log

**Comment by mrfelton** [comment]
This issue should now be resolved in the master branch. Fix will be included in our next release (which will be done once lnd 0.6.0 official has been released)

**Comment by dannydiekroeger** [comment]
I haven't been able to connect Zap to any of my LND 0.6.0-beta nodes, even with Zap 0.4.1. Is this still a known issue?

**Comment by jrosco** [comment]
@dannydiekroeger It works for me. I'm using Ubuntu 18 for both my Zap Wallet and LND. Maybe provide some logs, this could help the devs investigate.

**Comment by mrfelton** [comment]
@dannydiekroeger Could you try making a build from the `next` branch and testing that?

See https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md

**Comment by dannydiekroeger** [comment]
> @dannydiekroeger Could you try making a build from the `next` branch and testing that?
> 
> See https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md

Made a build from the ```next``` branch but still getting the same issue. My node is running on a cloud server and I *can* connect to it using other methods such as curl, a custom node script, and ride-the-lightning (which is an inferior product to the beautiful product that is ZAP :) )

Here's a dump of the logs from the dev console (with my IP redacted). One thing I've noticed is "useMacaroon" is undefined and "waitForCert" and "waitForMacaroon" are false, though I haven't looked into the code to know if that's relevant yet.

```
lnrpc:grpc Initializing LndGrpc with config: {host: "35.233.248.84:10009", cert: "/Users/danny/Desktop/personal/lightning/tls.cert", macaroon: "/Users/danny/Desktop/personal/lightning/admin.macaroon", waitForMacaroon: false, waitForCert: false, …}cert: "/Users/danny/Desktop/personal/lightning/tls.cert"host: "<my node's public IP>:10009"macaroon: "/Users/danny/Desktop/personal/lightning/admin.macaroon"protoDir: "node_modules/lnd-grpc/proto"useMacaroon: undefinedwaitForCert: falsewaitForMacaroon: false__proto__: Object +0ms
browser.js?34eb:183 lnrpc:grpc Connecting to lnd gRPC service +7ms
browser.js?34eb:183 lnrpc:grpc Attempting to determine wallet state +9ms
browser.js?34eb:183 lnrpc:service:WalletUnlocker Connecting to WalletUnlocker gRPC service +0ms
browser.js?34eb:183 lnrpc:service:WalletUnlocker Establishing gRPC connection to WalletUnlocker with proto file node_modules/lnd-grpc/proto/0.6.0-beta/lnrpc/rpc.proto +1ms
browser.js?34eb:183 lnrpc:service:WalletUnlocker Unable to connect to WalletUnlocker service +10s Error: Failed to connect before the deadline
    at checkState (client.js?ad5b:50)
    at setTimeout (channel.js?e974:290)
grpc.js?4619:280 Error: Failed to connect before the deadline
    at checkState (client.js?ad5b:50)
    at setTimeout (channel.js?e974:290)
```
More info is that I have an Lnd.conf file on my local machine at the normal location, but this file does not correspond to the node I'm trying to connect to. Again, not sure if that matters but just some extra info.

**Comment by mrfelton** [comment]
@dannydiekroeger I believe your issue is one of two things:

1) gRPC on port 10009 is not accessible from the machine that you are trying to connect from (test with telnet (`telnet <my nodes ip> 10009`)
2) You are trying to connect with an invalid TLS certificate. Paste your cert into https://sslshopper.com/certificate-decoder.html and verify that it includes the IP address that you are  trying to connect to (`<my nodes ip>`)

**Comment by dannydiekroeger** [comment]
@mrfelton Thanks for the advice. It seems to be number 2. When I decode the cert, it contains the IP addresses of localhost and the local cluster IP where the kubernetes pod is running, but it does not contain the *external* IP address, which is what matters for this.

My attempt at solving this was making sure the variable ```externalip=<my external ip>``` was set in my lnd.conf file, then deleting the tls.cert and tls.key files, then restarting lnd. This succeeded in generating a new cert, but this new cert still does not seem to include a reference to my external IP. 

Anyway, pretty sure its number 2. I will keep investigating and post my findings here. This seems to be more an issue with LND rather than Zap. Thanks for the assistance.

**Comment by dannybitgo** [comment]
Update: the fix was to set the following variable in my ``lnd.conf``` file on my node:
```
tlsextraip=<my external ip>
```
Then delete the files ```tls.cert``` and ```tls.key```.
Then restart the node, which will generate a new cert that now includes the external IP address.
Confirmed, now I can connect to my node with Zap. :)
👍 💯 👍 💯

**Comment by dannydiekroeger** [comment]
Update: the fix was to set the following variable in my ```lnd.conf``` file on my node:
```
tlsextraip=<my external ip>
```
Then delete the files ```tls.cert``` and ```tls.key```
Then restart the node, which will generate a new cert that now includes the external IP address.
Confirmed, now I can connect to my node with Zap. :)
👍 💯 👍 💯

**Comment by mrfelton** [comment]
Glad you got it sorted @dannydiekroeger . This one comes up over and over again. You wanna submit a PR for the troubleshooting guide?

https://github.com/LN-Zap/zap-desktop/blob/master/docs/TROUBLESHOOTING.md
