### ISSUE TITLE
Zap Wallet Stuck on "Fetching tickers" status (incompatible with lnd 0.6.x)

### ISSUE THREAD

**Issue by robbie2121** [LN-Zap/zap-desktop#1966]
## Description

I just upgraded to Pierre Rochard's node launcher v6.0.2 and to Zap v0.4.0. Everything appears to be working, LND and bitcoin node are connected. But when I open the Zap desktop app, it gets stuck on "Fetching tickers".

## Expected Behavior

Open Zap wallet successfully and see channels and funds

## Actual Behavior

Gets stuck on "Fetching tickers" status /  loading page

## Steps to Reproduce

- 1. Setup/run Pierre Rochard's node launcher v6.0.2
- 2. Setup Zap v0.4.0
- 3. Open Zap desktop app

## Context

Cannot fund wallet and see channels.

## Your Environment

- Zap version: 0.4.0
- Operating System and version: windows 10 enterprise 64bit
-Pierre Rochard's node launcher: 6.0.2
-LND v0.6-beta-rc3

**Comment by mrfelton** [comment]
This is a known issue. Zap 0.4.0 is not compatible with Lnd 0.6.0-rc2. This issue is fixed in the Zap `master` branch and will be included in our upcoming `0.4.1` release

**Comment by jakestpeter** [comment]
Same Issue Here

**Comment by Maghferat** [comment]
Same Issue also here (no Balance / Fetching tickers)

**Comment by jason-me** [comment]
Same here. Using Pierre Rochard's node launcher v6.0.2 & Zap v0.4.0

**Comment by jstylez13** [comment]
Sam here, looking forward to this fix.

**Comment by Maghferat** [comment]
if i try only recover my previous Zap wallet without using Pierre Rochard's node on ver.04, it stucks somewhere bitween 60-100%

**Comment by P0u1us** [comment]
I have manually build a full LND node on ubuntu and am using a seperate windows pc with zap wallet; and the result is the same: zap is stuck on fetching tickers; the annoying thing is that I have spent the last 3 days trying to figure out all possible error scenarios: ssl issues; cert issues; lnd connect issues; firewall issues; and many many more... the thing I am seriously missing is simply.... a debug log of zap! can that somehow be implemented so that at least there is some base info on the possible errors? for now I am looking forward to the 0.4.1 release !

**Comment by i22ie** [comment]
Same here: Zap Wallet Stuck on Fetching tickers. Windows 10 updates current.

**Comment by Zeno78** [comment]
Same issue, When will 4.1 be avail to use?

**Comment by mrfelton** [comment]
This issue should now be resolved in the new `Zap 0.4.1` release, which now supports `lnd 0.6.x`.

**Comment by P0u1us** [comment]
YIP GREAT it works now!
Thanks for the effort !!!!

**Comment by jason-me** [comment]
Thanks for the fix!! Will try again tonight!

**Comment by 1mdc** [comment]
Hi, I still have the same issue. lnd 0.6 beta and zap 0.4.1. Zap stuck at "Fetching tickers" screen.

**Comment by hubiktomas** [comment]
Me too

**Comment by hubiktomas** [comment]
Is it possible to reopen the issue?

**Comment by jooray** [comment]
Me too, please reopen. Zap 0.4.1-beta

When I run it from console, except for electron-builder stuff I see:

Unable to determine exact gRPC version: TypeError: Cannot read property 'version' of null

**Comment by RobertWilson2019** [comment]
Same issue again for me also.

**Comment by dawsy8888** [comment]
same issue

**Comment by mrfelton** [comment]
Hi. Please update to Zap 0.5.0 and let us know if the issue persists. Thanks.

**Comment by mrfelton** [comment]
I'm going to close this due to lack of activity. This was a known issue with BTCPay server in order versions of Zap & BTCPay Server. Updating Zap and BTCPay Server to the latest versions should resolve the issue.
