### ISSUE TITLE
Pending Channel. 

### ISSUE THREAD

**Issue by crippercrisp** [LN-Zap/zap-desktop#3706]
I opened the channel with 20k satoshi and its been 3 days and it hasnt changed. I chosen the slow fee. 
[https://blockstream.info/tx/fd52a3ec3bca423507077bb4639db9335b3a84fba99d7326162aa83006588a64](url)

## Actual Behavior

![Screenshot 2021-01-27 121243](https://user-images.githubusercontent.com/77501417/106027551-ff552e00-6098-11eb-9a32-405802eef2b6.png)
- Zap version:
- Operating System and version:

**Comment by bolatovumar** [comment]
@crippercrisp yeah, fees have been high lately so it's probably going to be a while until your transaction confirms.

**Comment by crippercrisp** [comment]
> 
> 
> @crippercrisp yeah, fees have been high lately so it's probably going to be a while until your transaction confirms.

any idea on how long it'll take?

**Comment by bolatovumar** [comment]
@crippercrisp no idea. Could take weeks or longer if fees don't go down quickly enough. See here for current fee estimates: https://twitter.com/CoreFeeHelper

**Comment by crippercrisp** [comment]
> 
> 
> @crippercrisp no idea. Could take weeks or longer if fees don't go down quickly enough. See here for current fee estimates: https://twitter.com/CoreFeeHelper

dang well thanks.

**Comment by brandoncollins7** [comment]
my transaction has been dropped from the mempool but zap still shows it as pending... How do I cancel and get my bitcoin back?

**Comment by pladohh** [comment]
I have same issue - attempted to open channel(s) and have been pending for over a week

Is there really no way to cancel the channel open request to free up the funds?

**Comment by mrfelton** [comment]
> Is there really no way to cancel the channel open request to free up the funds?

No, you broadcast a bitcoin transaction. You can't unbroadcast it.

**Comment by mrfelton** [comment]
> my transaction has been dropped from the mempool but zap still shows it as pending... How do I cancel and get my bitcoin back?

If your transaction was dropped from the mempool, you may need to try to run abandonchannel against your lnd node in order for it to unlock the funds.

https://api.lightning.community/#abandonchannel

**Comment by brandoncollins7** [comment]
I am just using the zap desktop wallet, I don't see any option to run commands anywhere?

**Comment by bolatovumar** [comment]
@brandoncollins7 you can not run the commands from Zap itself, you will have to run them from LND (you may need to install it yourself if you haven't already).

**Comment by beinghumble** [comment]
i have the same issue. it's been pending since Feb 17. new to lighting network and getting mynode setup. had no idea it would take this long. my fee was set to slow...$0.15. 

this is the current rate 1wk:  
11.0 sat/byte  $1.31
Min:   5.0 sat/byte  $0.59. 

any thoughts on how long it would take to clear with $0.15. is there a way to check if it's stuck or cancel the channel Funding.

![image](https://user-images.githubusercontent.com/80086376/110070803-c1f35880-7d48-11eb-90ef-55c70a761f1b.png)

**Comment by grubeli** [comment]
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address

**Comment by pladohh** [comment]
Has anyone tried this?

Wouldn't that amount to a double spend if the open channel transaction is still in the mem pool?

Thanks

**Comment by chris-aeviator** [comment]
It would be nice to know (and see in the zap UI) how many confirmations an opening transaction has received. I can see for example in mempool, that I have 2 confirmations on the channel funding transaction, while zap still show's (just) a `pending open` notification. 

A more nice experience would be if the UI informs me what's the condition of changing that state ("waiting for confirmtion of another x ...")

**Comment by escapedcat** [comment]
Might be related or duplicates #3702
